apiVersion: v1
kind: ConfigMap
metadata:
  name: server-params
  namespace: default
data:
  SERVICE:master
  P4PORT:1666
  P4ROOT:/data/opt/perforce/servers/master
  USER:admin
  PASSWD:ILikeGitBetter
