apiVersion: v1
kind: Service
metadata:
  name: perforce-server
  labels:
    name: perforce-server
spec:
  type: NodePort
  ports:
    - port: 1666
      nodePort: 30767
      name: p4d
  selector:
    app: perforce-server
