apiVersion: apps/v1
kind: Deployment
metadata:
  name: perforce-server-dep
  labels:
    app: perforce-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perforce-server
  template:
    metadata:
      labels:
        app: perforce-server
    spec:
      volumes:
      - name: my-do-volume
        persistentVolumeClaim:
          claimName: perforce-pvc
      containers:
      - name: perforce-server
        image: jascase901/perforce-server:latest
        volumeMounts:
        - mountPath: "/data"
          name: my-do-volume
        ports:
        - containerPort: 1666
        envFrom:
        - configMapRef:
            name: server-params
